### ISSUE TITLE
VehiclePositionをmapで返す関数の実装

### ISSUE THREAD

**Issue by EF1659** [ITNS-LAB/gtfs-gorm#1]
現在VehiclePositionを返す関数(ParseVehiclePositionPb)の返り値はスライスですが、tripIdをキーとしたmapで返す関数の実装を希望します。

**Comment by Atsu06** [comment]
VehiclePositionとTripupdateにtripIdをキーとしたmapを返す関数の実装を行いました。
さらに、同名のパッケージが存在したのでそれらを回避するようにディレクトリの構造を修正しました。
